name: Auto Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install cloudflared
      run: |
        curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
        chmod +x cloudflared
        sudo mv cloudflared /usr/local/bin/

    - name: Save CF token to file
      run: |
        echo "${{ secrets.CF_ACCESS_TOKEN }}" > /tmp/cf-token

    - name: Deploy to server with PNPM
      run: |
        ssh -o StrictHostKeyChecking=no \
            -o ProxyCommand="cloudflared access ssh --token-file /tmp/cf-token --hostname ssh.robogo.website" \
            root@ssh.robogo.website << 'EOF'
          cd RoboGo_Dashboard/server/
          git pull origin main
          pnpm install
          pnpm run build
          pm2 restart robogo_backend || pm2 start server.js --name robogo_backend
        EOF
